#CI项目
name: ipq60xx-sdf-4.4

#CI计划
on:
  # 手动执行
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-sdf-4.4

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ipq60xx-sdf-4.4
      #源码
      REPO_SOURCE: sdf8057
      #源码地址
      REPO_URL: https://github.com/zhoufla/ipq6000.git
      #源码分支
      REPO_BRANCH: master
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/sdf/passwall.config
